Update bsp to 2.1.0-M3
scalacenter/bloop pull request #1845
Opened 2022-11-03 13:41 UTC by lwronski

2022-11-04 08:16 UTC, lwronski commented
> Could you make sure you are able to start it with JDK 8? Last time I tried the updated BSP would on work on older JDK. I haven't been able to find why.

Bsp uses `jsoniter-scala` which has recently dropped support for JDK 8 - https://github.com/plokhotnyuk/jsoniter-scala/pull/860/files. That's probably why you couldn't run bloop with JDK 8

2022-11-04 08:34 UTC, tgodzik commented
Ach thanks! We should probably change jsoniter to an older version in BSP then. Unless we want to start dropping JDK 8 everywhere :thinking:

2022-11-04 08:37 UTC, tgodzik commented
> Ach thanks! We should probably change jsoniter to an older version in BSP then. Unless we want to start dropping JDK 8 everywhere thinking

Or we should change BSP to using JDK 11 at the least. Can you raise an issue in BSP so that they are aware of that? I think at this point it might be fine to start dropping JDK 8, especially since Bloop isn't used as a library anywhere.

2022-11-07 15:25 UTC, ckipp01 commented
Regarding jdk 8, did sbt not have any issues with this? https://github.com/sbt/sbt/pull/6985

2022-11-08 13:36 UTC, tgodzik commented
@lwronski Let's revert jsoniter update in BSP for now to the last one working with JDK8, we should also be able to pin the version in scala steward for now.

2022-11-14 14:17 UTC, tgodzik commented on build.sbt
> +      Dependencies.jsoniterCore,
Could you also bump jsoniter to the latest version that supports JDK 8 ?

2022-11-21 15:01 UTC, tgodzik requested changes
Looks good! Could you only update some of the expect tests? They don't expect the additional None. Alternatively, we could  change the string representation in tests so that they don't fail with new fields.

2022-11-23 12:37 UTC, tgodzik approved these changes
LGTM!

2022-11-23 12:38 UTC, merged